export const eventCategories = [
    "Category",
    "Auto, Boat and Air",
    "Business & Professional",
    "Charity & Causes",
    "Community & Culture",
    "Family & Education",
    "Fashion and Beauty",
    "Film, Media, & Entertainment",
    "Food & Drink",
    "Government & Politics",
    "Health & Wellness",
    "Hobbies & Special Interest",
    "Home & Lifestyle",
    "Music",
    "Other",
    "Performing & Visual Arts",
    "Religion & Spirituality",
    "School Activities",
    "Science & Technology",
    "Seasonal & Holiday",
    "Sports & Fitness",
    "Travel & Outdoor"
]